ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.github.dmitriyushakov.srv_decompiler.api.ContentNegotiationInstallKt.contentNegotiationInstallModule
      - com.github.dmitriyushakov.srv_decompiler.api.WebSocketsInstallKt.installWebSocketsModule
      - com.github.dmitriyushakov.srv_decompiler.statuses.StatusesKt.statusesModule
      - com.github.dmitriyushakov.srv_decompiler.api.IndexRegistryAPIModuleKt.module
      - com.github.dmitriyushakov.srv_decompiler.api.DecompilersAPIModuleKt.decompilersModule
      - com.github.dmitriyushakov.srv_decompiler.api.IndexerStatusAPIModuleKt.indexerStatusModule
      - com.github.dmitriyushakov.srv_decompiler.common.StaticResourcesModuleKt.servingStaticResourcesModule
      - com.github.dmitriyushakov.srv_decompiler.indexer.IndexerModuleKt.indexerModule